<html>
<head>
    <meta charset=utf-8>
    <title>Sales Lead</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
</head>

<body style="font-family:helvetical,arial,san-serif;color:#333;">

<table>
<tr>
<td width="25%"><b>Date:</b></td><td width="*">${date}</td>
</tr>
<tr>
<td><b>To:</b></td><td>${fb.dealerName}</td>
</tr>
<tr>
<td></td><td>${fb.dealerAddress1}</td>
</tr>
<tr>
<td></td><td>${fb.dealerAddress2}</td>
</tr>
<tr>
<td></td><td>${fb.dealerCity}</td>
</tr>
<tr>
<td></td><td>${fb.dealerState}</td>
</tr>
<tr>
<td></td><td>${fb.dealerZip}</td>
</tr>
<tr>
<td></td><td>${fb.dealerPhone}</td>
</tr>
<tr>
<td></td><td>${fb.dealerEmail}</td>
</tr>
<tr>
<td><b>ESS #:</b></td><td>${fb.dealerEss}</td>
</tr>
<tr>
<td><b>From:</b></td><td>Canon U.S.A., Inc.</td>
</tr>
</table>
<br/><br/>
--------------------------------------------------------------------------------------------------<br/>
<br/>
Below is a Sales Lead generated by the Canon USA internet website via the Dealer Locator leads form:
<br/><br/>
<table>
<tr>
<td width="40%">Salutation:</td><td width="*">${fb.salutation}</td>
</tr>
<tr>
<td>First Name:</td><td>${fb.firstname}</td>
</tr>
<tr>
<td>Last Name:</td><td>${fb.lastname}</td>
</tr>
<tr>
<td>Job Title:</td><td>${fb.jobtitle}</td>
</tr>
<tr>
<td>Company:</td><td>${fb.company}</td>
</tr>
<tr>
<td>Address 1:</td><td>${fb.address1}</td>
</tr>
<tr>
<td>Address 2:</td><td>${fb.address2}</td>
</tr>
<tr>
<td>City:</td><td>${fb.city}</td>
</tr>
<tr>
<td>State:</td><td>${fb.state}</td>
</tr>
<tr>
<td>Zip:</td><td>${fb.zip}</td>
</tr>
<tr>
<td>Country:</td><td>${fb.country}</td>
</tr>
<tr>
<td>Phone:</td><td>${fb.phone}</td>
</tr>
<tr>
<td>Fax:</td><td>${fb.fax}</td>
</tr>
<tr>
<td>Email Address:</td><td>${fb.email}</td>
</tr>
<tr>
<td>Product:</td><td>${fb.modelName}</td>
</tr>
</table>

</body>
</html>